from __future__ import annotations
from enum import StrEnum

class Direction(StrEnum):
    UP="UP"; DOWN="DOWN"; UNRESOLVED="UNRESOLVED"
class StructureState(StrEnum):
    FORMING="FORMING"; CANDIDATE="CANDIDATE"; ACTIVE="ACTIVE"; CONFIRMED="CONFIRMED"; FINALIZED="FINALIZED"; INVALIDATED="INVALIDATED"; UNRESOLVED="UNRESOLVED"
class Timeframe(StrEnum):
    WEEKLY="weekly"; DAILY="daily"; M120="120m"; M30="30m"; M5="5m"
class Market(StrEnum): CN_A="CN_A"
class StrokeMode(StrEnum): STRICT_OLD="STRICT_OLD"; RELAXED_LATE="RELAXED_LATE"
class DataConfidence(StrEnum):
    HIGH="HIGH"; MEDIUM="MEDIUM"; LOW="LOW"; STALE="STALE"; DATA_INCOMPLETE="DATA_INCOMPLETE"
class FractalType(StrEnum): TOP="TOP"; BOTTOM="BOTTOM"
class StrokePhase(StrEnum): EXTENDING="EXTENDING"; REVERSAL_FRACTAL_FORMING="REVERSAL_FRACTAL_FORMING"
class IssueSeverity(StrEnum): INFO="INFO"; WARNING="WARNING"; ERROR="ERROR"; BLOCKER="BLOCKER"
class SegmentState(StrEnum):
    SEED="SEED"; ACTIVE="ACTIVE"; STROKE_BREAK_PENDING="STROKE_BREAK_PENDING"; CASE1_PENDING="CASE1_PENDING"; CASE2_PENDING="CASE2_PENDING"; FINALIZED="FINALIZED"; INVALIDATED="INVALIDATED"
class SegmentCase(StrEnum): NONE="NONE"; CASE1="CASE1"; CASE2="CASE2"
class SegmentBreakState(StrEnum): NONE="NONE"; STROKE_BREAK_PENDING="STROKE_BREAK_PENDING"; BREAK_FAILED="BREAK_FAILED"; BREAK_CONFIRMED="BREAK_CONFIRMED"
class FeatureFractalType(StrEnum): FEATURE_TOP="FEATURE_TOP"; FEATURE_BOTTOM="FEATURE_BOTTOM"
class CenterState(StrEnum):
    FORMING="FORMING"; CONFIRMED="CONFIRMED"; EXTENDING="EXTENDING"; LEAVING_UP="LEAVING_UP"; LEAVING_DOWN="LEAVING_DOWN"; RETURNING="RETURNING"; NEW_CENTER_PENDING="NEW_CENTER_PENDING"; EXPANSION_PENDING="EXPANSION_PENDING"; DESTROYED="DESTROYED"; FINALIZED="FINALIZED"
class CenterRelationType(StrEnum):
    SAME_CENTER_EXTENSION="SAME_CENTER_EXTENSION"; INDEPENDENT_UP_NEW_CENTER="INDEPENDENT_UP_NEW_CENTER"; INDEPENDENT_DOWN_NEW_CENTER="INDEPENDENT_DOWN_NEW_CENTER"; EXPANSION_PENDING="EXPANSION_PENDING"; UNRESOLVED="UNRESOLVED"
class CenterEventType(StrEnum):
    CENTER_UP_BREAK_RETURN_OUTSIDE="CENTER_UP_BREAK_RETURN_OUTSIDE"; CENTER_DOWN_BREAK_RETURN_OUTSIDE="CENTER_DOWN_BREAK_RETURN_OUTSIDE"
class TrendClassification(StrEnum):
    CONSOLIDATION="CONSOLIDATION"; UPTREND="UPTREND"; DOWNTREND="DOWNTREND"; UNRESOLVED="UNRESOLVED"
class TrendState(StrEnum):
    FORMING="FORMING"; CLASSIFIABLE="CLASSIFIABLE"; EXTENDING="EXTENDING"; COMPLETION_CANDIDATE="COMPLETION_CANDIDATE"; COMPLETED="COMPLETED"; UNRESOLVED="UNRESOLVED"
class DivergenceType(StrEnum):
    NONE="NONE"; TREND_BOTTOM_DIVERGENCE="TREND_BOTTOM_DIVERGENCE"; TREND_TOP_DIVERGENCE="TREND_TOP_DIVERGENCE"; CONSOLIDATION_BOTTOM_DIVERGENCE="CONSOLIDATION_BOTTOM_DIVERGENCE"; CONSOLIDATION_TOP_DIVERGENCE="CONSOLIDATION_TOP_DIVERGENCE"; MOMENTUM_WEAKENING="MOMENTUM_WEAKENING"; UNRESOLVED="UNRESOLVED"
class DivergenceState(StrEnum):
    NONE="NONE"; WEAKENING="WEAKENING"; CANDIDATE="CANDIDATE"; FORMING="FORMING"; CONFIRMED="CONFIRMED"; INVALIDATED="INVALIDATED"
class ChanSignalType(StrEnum):
    FIRST_BUY="FIRST_BUY"; SECOND_BUY="SECOND_BUY"; THIRD_BUY="THIRD_BUY"; FIRST_SELL="FIRST_SELL"; SECOND_SELL="SECOND_SELL"; THIRD_SELL="THIRD_SELL"; STRONG_CLASS2_BUY="STRONG_CLASS2_BUY"; CENTER_CLASS2_BUY="CENTER_CLASS2_BUY"; HIGH_LEVEL_CLASS2_SELL="HIGH_LEVEL_CLASS2_SELL"
class SignalState(StrEnum):
    FORMING="FORMING"; CANDIDATE="CANDIDATE"; CONFIRMED="CONFIRMED"; INVALIDATED="INVALIDATED"
class SecondBuyTrackerState(StrEnum):
    WAIT_FIRST_UP_MOVE="WAIT_FIRST_UP_MOVE"; FIRST_UP_MOVE_FORMING="FIRST_UP_MOVE_FORMING"; FIRST_UP_MOVE_COMPLETED="FIRST_UP_MOVE_COMPLETED"; WAIT_RETRACEMENT="WAIT_RETRACEMENT"; RETRACEMENT_FORMING="RETRACEMENT_FORMING"; SECOND_BUY_CANDIDATE="SECOND_BUY_CANDIDATE"; SECOND_BUY_CONFIRMED="SECOND_BUY_CONFIRMED"; SECOND_BUY_INVALIDATED="SECOND_BUY_INVALIDATED"
class ThirdBuyTrackerState(StrEnum):
    WAIT_DEPARTURE="WAIT_DEPARTURE"; DEPARTURE_FORMING="DEPARTURE_FORMING"; DEPARTURE_COMPLETED="DEPARTURE_COMPLETED"; WAIT_FIRST_RETURN="WAIT_FIRST_RETURN"; FIRST_RETURN_FORMING="FIRST_RETURN_FORMING"; THIRD_BUY_CONFIRMED="THIRD_BUY_CONFIRMED"; THIRD_BUY_FAILED="THIRD_BUY_FAILED"
